#ifndef GAME_MAPITEMS_FNG_H
#define GAME_MAPITEMS_FNG_H

enum
{
	TILE_FNG_SPIKE_GOLD = 7,
	TILE_FNG_SPIKE_NORMAL,
	TILE_FNG_SPIKE_RED,
	TILE_FNG_SPIKE_BLUE,
	TILE_FNG_SCORE_RED,
	TILE_FNG_SCORE_BLUE,

	TILE_FNG_SPIKE_GREEN = 14,
	TILE_FNG_SPIKE_PURPLE,

	TILE_FNG_SPAWN = 192,
	TILE_FNG_SPAWN_RED,
	TILE_FNG_SPAWN_BLUE,
	TILE_FNG_FLAG_RED,
	TILE_FNG_FLAG_BLUE,
	TILE_FNG_SHIELD,
	TILE_FNG_HEART,
	TILE_FNG_SHOTGUN,
	TILE_FNG_GRENADE,
	TILE_FNG_NINJA,
	TILE_FNG_LASER,

	TILE_FNG_SPIKE_OLD1 = 208,
	TILE_FNG_SPIKE_OLD2,
	TILE_FNG_SPIKE_OLD3
};

#endif
