#ifndef GAME_MAPITEMS_INSTA_H
#define GAME_MAPITEMS_INSTA_H

enum
{
	TILE_FNG_SPIKE_GOLD = 7,
	TILE_FNG_SPIKE_NORMAL = 8,
	TILE_FNG_SPIKE_RED = 9,
	TILE_FNG_SPIKE_BLUE = 10,

	TILE_FNG_SPIKE_GREEN = 14,
	TILE_FNG_SPIKE_PURPLE = 15,
};

#endif
