#ifndef GAME_MAPITEMS_VANILLA_H
#define GAME_MAPITEMS_VANILLA_H

enum
{
	TILE_VANILLA_SPAWN = 192,
	TILE_VANILLA_SPAWN_RED,
	TILE_VANILLA_SPAWN_BLUE,
	TILE_VANILLA_FLAG_RED,
	TILE_VANILLA_FLAG_BLUE,
	TILE_VANILLA_SHIELD,
	TILE_VANILLA_HEART,
	TILE_VANILLA_SHOTGUN,
	TILE_VANILLA_GRENADE,
	TILE_VANILLA_NINJA,
	TILE_VANILLA_LASER,
};

#endif
