'\" t
.\"     Title: DDNet
.\"    Author: DDNet Contributors
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: v1.0.0
.\"    Manual: DDNet Manual
.\"    Source: DDNet 11.7.2
.\"  Language: English
.\"
.TH "DDNET" "6" "v1\&.0\&.0" "DDNet 11\&.7\&.2" "DDNet Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
DDNet \- Starts the DDNet client\&.
.SH "SYNOPSIS"
.sp
\fBDDNet\fR [\fIOPTION\fR]\&... [\-f \fICONFIG_FILE\fR]\&...
.SH "DESCRIPTION"
.sp
DDraceNetwork (DDNet) is an actively maintained version of \fBDDRace\fR, a \fBTeeworlds\fR modification with a unique cooperative gameplay\&.
.SH "EXAMPLES"
.sp
\fBDDNet\fR \-f myfile\&.cfg
.sp
\fBDDNet\fR \-f myfile\&.cfg \-f myfile2\&.cfg
.sp
\fBDDNet\fR \*(Aqcl_showhud 0\*(Aq \*(Aqplayer_name "nameless tee"\*(Aq
.SH "OPTIONS"
.SS "Configuration file"
.PP
\fB\-f\fR \fICONFIGURATION_FILE\fR
.RS 4
Load
\fICONFIGURATION_FILE\fR
instead of default
\fIsettings_ddnet\&.cfg\fR
.RE
.SS "Other options"
.sp
All options can be found here: https://ddnet\&.org/settingscommands/
.SH "RESOURCES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBWebsite\fR:
https://ddnet\&.org/
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBRSS\fR:
https://ddnet\&.org/feed/
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBForum\fR:
https://forum\&.ddnet\&.org/
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBDiscord\fR:
https://ddnet\&.org/discord
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBSource\fR:
https://github\&.com/ddnet/ddnet
.RE
.SH "REPORTING BUGS"
.sp
Report any issues here: https://github\&.com/ddnet/ddnet/issues
.SH "CONTRIBUTING"
.sp
You can contribute by opening a pull request here: https://github\&.com/ddnet/ddnet/pulls
.SH "COPYRIGHT"
.sp
Free use of this software is granted under the terms of the MIT License\&.
.sp
You can read the license here: https://github\&.com/ddnet/ddnet/blob/master/license\&.txt
.SH "AUTHOR"
.PP
\fBDDNet Contributors\fR
.RS 4
Author.
.RE
