#include "gameworld_test.h"

#include <base/fs.h>
#include <base/io.h>
#include <base/math.h>
#include <base/str.h>

#include <game/prng.h>
#include <game/server/entities/character.h>
#include <game/server/gamecontext.h>
#include <game/server/player.h>
#include <game/server/teehistorian_reader.h>

#include <gtest/gtest.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>

// ---------------------------------------------------------------------
// Feeds a recorded teehistorian session's inputs back into a real
// `CGameWorld` (on the same map the recording was made on) and compares the
// resulting character positions against the positions the recording says
// actually happened. See `TeeHistorianReplay.RealRecordings` below.
// ---------------------------------------------------------------------

namespace
{

	// A single (tick, client) position mismatch found during replay.
	struct CDivergence
	{
		int m_Tick;
		int m_ClientId;
		int m_RecordedX, m_RecordedY;
		int m_ReplayedX, m_ReplayedY;
	};

	struct CReplayReport
	{
		// Set when the recording's header doesn't match the map the fixture loaded; nothing else in
		// this report is meaningful in that case.
		std::string m_MapMismatchReason;

		// False when the recording had no usable prng_description, so random draws (teleport
		// destinations) cannot be reproduced.
		bool m_PrngSeeded = false;

		bool m_ReaderError = false;
		std::string m_ReaderErrorMessage;

		int m_TicksReplayed = 0;
		int m_PositionsCompared = 0;
		int m_DivergentComparisons = 0;
		// Distinct ticks with at least one divergent client, i.e. `<= m_DivergentComparisons`.
		int m_DivergentTicks = 0;
		// The first 10 divergent (tick, client) comparisons, in the order they were found.
		std::vector<CDivergence> m_vFirstDivergences;
		// PLAYER_DIFF events seen for a client the replay never saw a PLAYER_NEW for, meaning the
		// recording started mid-session (persistent state across a map reload); the replay force-spawns
		// such a client at the diff's position instead of the actual (unrecorded) spawn point.
		int m_ImplicitSpawns = 0;
		int m_aDivergentPerClient[MAX_CLIENTS] = {0};
		int m_aFirstDivergentTick[MAX_CLIENTS] = {0};
	};

	// Per-client bookkeeping the replay needs to mirror what the recording implies about a player,
	// without inventing information the recording doesn't actually contain (e.g. spawn selection).
	struct CReplayClient
	{
		bool m_Joined = false;
		bool m_Alive = false;
		vec2 m_RecordedPos = vec2(0.0f, 0.0f);
		CNetObj_PlayerInput m_PendingInput = {};
	};

} // namespace

// Drives a real `CGameContext`/`CGameWorld` (via the same `GameWorld` fixture the golden physics
// tests use) with the inputs from a teehistorian recording, one server tick at a time, comparing
// the resulting character positions against what the recording says they were.
class CReplayWorld : public GameWorld // NOLINT(readability-identifier-naming)
{
public:
	// `GameWorld` is a gtest fixture (`::testing::Test`), which normally gets its `TestBody`
	// generated by `TEST_F`. `CReplayWorld` is instantiated directly instead (once per recording,
	// from inside a single `TEST`), so it needs a trivial one of its own.
	void TestBody() override {}

	CReplayClient m_aClients[MAX_CLIENTS];
	int m_SimTick = -1;
	CPrng m_ReplayPrng;

	/**
	 * Seeds the world's random number generator from the recording's `prng_description`, which
	 * `CPrng::Seed` writes as `pcg-xsh-rr:<seed0>:<seed1>` with both halves in full hex. Teleport
	 * destinations are chosen with `CWorldCore::RandomOr0`, so without the recorded seed a tee
	 * that hits a teleporter with several exits takes a different one than it did originally and
	 * every later position diverges. Returns false if the description is absent or unparsable,
	 * which older recordings may be.
	 */
	bool SeedPrngFrom(const std::string &Description)
	{
		unsigned Seed0Hi, Seed0Lo, Seed1Hi, Seed1Lo;
		if(sscanf(Description.c_str(), "pcg-xsh-rr:%08x%08x:%08x%08x", &Seed0Hi, &Seed0Lo, &Seed1Hi, &Seed1Lo) != 4)
		{
			return false;
		}
		uint64_t aSeed[2];
		aSeed[0] = ((uint64_t)Seed0Hi << 32) | Seed0Lo;
		aSeed[1] = ((uint64_t)Seed1Hi << 32) | Seed1Lo;
		m_ReplayPrng.Seed(aSeed);
		GameServer()->m_World.m_Core.m_pPrng = &m_ReplayPrng;
		return true;
	}

	void EnsurePlayer(int ClientId)
	{
		if(!m_aClients[ClientId].m_Joined)
		{
			GameServer()->CreatePlayer(ClientId, TEAM_GAME, false, -1);
			m_aClients[ClientId].m_Joined = true;
		}
	}

	// Advances the world by exactly one tick, applying the last-known input to every currently
	// alive replayed character first. This mirrors the real server's main loop, which calls
	// `OnClientPredictedEarlyInput`/`OnClientPredictedInput` every tick regardless of whether new
	// input arrived (reusing the last input otherwise), immediately before `OnTick`.
	void SimulateOneTick(CReplayReport *pReport)
	{
		for(int ClientId = 0; ClientId < MAX_CLIENTS; ClientId++)
		{
			if(!m_aClients[ClientId].m_Alive)
				continue;
			CPlayer *pPlayer = GameServer()->m_apPlayers[ClientId];
			CCharacter *pChr = pPlayer ? pPlayer->GetCharacter() : nullptr;
			if(pChr == nullptr)
				continue;
			pChr->OnDirectInput(&m_aClients[ClientId].m_PendingInput);
			pChr->OnPredictedInput(&m_aClients[ClientId].m_PendingInput);
		}
		GameServer()->OnTick();
		pReport->m_TicksReplayed++;
	}

	// Compares every currently alive replayed character's position against the ground truth the
	// recording last established for it. This is valid for `Tick` regardless of whether anything
	// was actually written for `Tick` in the recording: the writer only emits a chunk when a
	// player's position differs from the previous tick's, so "no chunk" means "unchanged".
	void CompareAllAlive(int Tick, CReplayReport *pReport)
	{
		bool AnyDivergenceThisTick = false;
		for(int ClientId = 0; ClientId < MAX_CLIENTS; ClientId++)
		{
			CReplayClient &Client = m_aClients[ClientId];
			if(!Client.m_Alive)
				continue;
			CPlayer *pPlayer = GameServer()->m_apPlayers[ClientId];
			CCharacter *pChr = pPlayer ? pPlayer->GetCharacter() : nullptr;

			const int RecordedX = round_to_int(Client.m_RecordedPos.x);
			const int RecordedY = round_to_int(Client.m_RecordedPos.y);
			// A missing character where the recording says one is alive is itself a divergence.
			const int ReplayedX = pChr ? round_to_int(pChr->Core()->m_Pos.x) : RecordedX + 1;
			const int ReplayedY = pChr ? round_to_int(pChr->Core()->m_Pos.y) : RecordedY + 1;

			pReport->m_PositionsCompared++;
			if(!pChr || RecordedX != ReplayedX || RecordedY != ReplayedY)
			{
				pReport->m_DivergentComparisons++;
				if(pReport->m_aDivergentPerClient[ClientId] == 0)
					pReport->m_aFirstDivergentTick[ClientId] = Tick;
				pReport->m_aDivergentPerClient[ClientId]++;
				AnyDivergenceThisTick = true;
				if(pReport->m_vFirstDivergences.size() < 10)
				{
					pReport->m_vFirstDivergences.push_back({Tick, ClientId, RecordedX, RecordedY, ReplayedX, ReplayedY});
				}
			}
		}
		if(AnyDivergenceThisTick)
		{
			pReport->m_DivergentTicks++;
		}
	}

	void ApplyEvent(const CTeeHistorianEvent &Event, CReplayReport *pReport)
	{
		if(Event.m_ClientId < 0 || Event.m_ClientId >= MAX_CLIENTS)
		{
			return;
		}
		CReplayClient &Client = m_aClients[Event.m_ClientId];
		switch(Event.m_Type)
		{
		case TEEHISTORIAN_READER_EVENT_JOIN:
			EnsurePlayer(Event.m_ClientId);
			break;

		case TEEHISTORIAN_READER_EVENT_DROP:
			if(Client.m_Alive)
			{
				CPlayer *pPlayer = GameServer()->m_apPlayers[Event.m_ClientId];
				if(pPlayer)
					pPlayer->KillCharacter();
			}
			Client.m_Alive = false;
			Client.m_Joined = false;
			break;

		case TEEHISTORIAN_READER_EVENT_PLAYER_NEW:
		{
			EnsurePlayer(Event.m_ClientId);
			CPlayer *pPlayer = GameServer()->m_apPlayers[Event.m_ClientId];
			const vec2 Pos = vec2((float)Event.m_X, (float)Event.m_Y);
			pPlayer->ForceSpawn(Pos);
			Client.m_Alive = true;
			Client.m_RecordedPos = Pos;
			break;
		}

		case TEEHISTORIAN_READER_EVENT_PLAYER_DIFF:
		{
			const vec2 Pos = vec2((float)Event.m_X, (float)Event.m_Y);
			if(!Client.m_Alive)
			{
				// The recording started mid-session: this client was already alive when
				// recording began, so there was no PLAYER_NEW establishing their spawn.
				EnsurePlayer(Event.m_ClientId);
				CPlayer *pPlayer = GameServer()->m_apPlayers[Event.m_ClientId];
				pPlayer->ForceSpawn(Pos);
				Client.m_Alive = true;
				pReport->m_ImplicitSpawns++;
			}
			Client.m_RecordedPos = Pos;
			break;
		}

		case TEEHISTORIAN_READER_EVENT_PLAYER_OLD:
			if(Client.m_Alive)
			{
				CPlayer *pPlayer = GameServer()->m_apPlayers[Event.m_ClientId];
				if(pPlayer)
					pPlayer->KillCharacter();
			}
			Client.m_Alive = false;
			break;

		case TEEHISTORIAN_READER_EVENT_INPUT_NEW:
		case TEEHISTORIAN_READER_EVENT_INPUT_DIFF:
			Client.m_PendingInput = Event.m_Input;
			break;

		default:
			// Not relevant to physics: TICK_SKIP is handled purely via `Event.m_Tick` by the
			// caller, and everything else (team assignment, chat, rcon, finishes, ...) doesn't
			// move a character.
			break;
		}
	}

	// Replays every event in `vFile` against a fresh world, tick by tick, and reports how the
	// resulting positions compared to the ones the recording says actually happened.
	CReplayReport Replay(const std::vector<unsigned char> &vFile)
	{
		CReplayReport Report;

		CTeeHistorianReader Reader;
		char aError[256];
		if(!Reader.Open(vFile.data(), vFile.size(), aError, sizeof(aError)))
		{
			Report.m_ReaderError = true;
			Report.m_ReaderErrorMessage = aError;
			return Report;
		}

		if(Reader.Header().m_aMapName != "coverage")
		{
			char aReason[256];
			str_format(aReason, sizeof(aReason), "recording is for map '%s', fixture loaded 'coverage'", Reader.Header().m_aMapName.c_str());
			Report.m_MapMismatchReason = aReason;
			return Report;
		}

		Report.m_PrngSeeded = SeedPrngFrom(Reader.Header().m_aPrngDescription);

		CTeeHistorianEvent Event;
		bool HaveEvent = Reader.NextEvent(&Event);
		while(HaveEvent)
		{
			const int Tick = Event.m_Tick;
			// Ticks strictly between the last one we simulated and this event's tick had no
			// recorded change at all: simulate and compare them using the carried-forward ground
			// truth before touching anything this event says.
			for(int T = m_SimTick + 1; T < Tick; T++)
			{
				SimulateOneTick(&Report);
				CompareAllAlive(T, &Report);
			}
			if(Tick > m_SimTick)
			{
				SimulateOneTick(&Report);
				m_SimTick = Tick;
			}

			ApplyEvent(Event, &Report);

			// Multiple events can share the same tick (e.g. two clients' positions both changed).
			// Only compare once every event for this tick has been applied.
			CTeeHistorianEvent NextEvent;
			const bool HaveNext = Reader.NextEvent(&NextEvent);
			if(!HaveNext || NextEvent.m_Tick != Tick)
			{
				CompareAllAlive(Tick, &Report);
			}
			Event = NextEvent;
			HaveEvent = HaveNext;
		}

		Report.m_ReaderError = Reader.Error();
		Report.m_ReaderErrorMessage = Reader.ErrorMessage();
		return Report;
	}
};

// Replays every *.teehistorian recording found in `DDNET_TEEHISTORIAN_TEST_DIR` (skipped by
// default, same opt-in as `TeeHistorianReader.RealRecordings`) against a fresh `coverage` world
// and compares the resulting positions against what the recording says actually happened.
//
// Divergence is a plausible, informative outcome, not just a bug in this harness: this is the
// first time decoded teehistorian ticks/inputs are checked against real physics, so a mismatch
// can point at the implicit-tick reconstruction, input application ordering, spawn placement, or
// tuning zones just as easily as at this harness. Comparisons never use a tolerance -- positions
// are effectively integers (`round_to_int`, matching how the recording itself rounds them), so
// they either match exactly or they tell you something. If any recording diverges, the full
// findings are printed and the test is skipped (not silently passed) rather than failed outright,
// since pinpointing the divergence is the deliverable, not a fix to the physics code.
TEST(TeeHistorianReplay, RealRecordings)
{
	const char *pDir = getenv("DDNET_TEEHISTORIAN_TEST_DIR");
	if(!pDir)
	{
		GTEST_SKIP() << "DDNET_TEEHISTORIAN_TEST_DIR not set";
	}

	std::vector<std::string> vNames;
	fs_listdir(
		pDir, [](const char *pName, int IsDir, int, void *pUser) -> int {
			if(!IsDir && str_endswith(pName, ".teehistorian"))
			{
				((std::vector<std::string> *)pUser)->emplace_back(pName);
			}
			return 0;
		},
		0, &vNames);
	std::sort(vNames.begin(), vNames.end());

	ASSERT_FALSE(vNames.empty()) << "no *.teehistorian files in " << pDir;

	bool AnyComparisonMade = false;
	std::string DivergenceSummary;

	for(const std::string &Name : vNames)
	{
		char aPath[IO_MAX_PATH_LENGTH];
		str_format(aPath, sizeof(aPath), "%s/%s", pDir, Name.c_str());

		IOHANDLE File = io_open(aPath, IOFLAG_READ);
		ASSERT_TRUE(File) << aPath;
		void *pData;
		unsigned DataSize;
		const bool ReadOk = io_read_all(File, &pData, &DataSize);
		io_close(File);
		ASSERT_TRUE(ReadOk) << aPath;

		std::vector<unsigned char> vFile((unsigned char *)pData, (unsigned char *)pData + DataSize);
		free(pData);

		CReplayWorld World;
		CReplayReport Report = World.Replay(vFile);

		if(!Report.m_MapMismatchReason.empty())
		{
			printf("%s: skipped, %s\n", aPath, Report.m_MapMismatchReason.c_str());
			continue;
		}

		EXPECT_FALSE(Report.m_ReaderError) << aPath << ": " << Report.m_ReaderErrorMessage;
		if(Report.m_ReaderError)
		{
			continue;
		}

		printf("%s: %d ticks replayed, %d positions compared, %d divergent comparison(s) across %d tick(s)%s\n",
			aPath, Report.m_TicksReplayed, Report.m_PositionsCompared, Report.m_DivergentComparisons,
			Report.m_DivergentTicks, Report.m_ImplicitSpawns ? " (implicit spawn(s) seen)" : "");
		for(int c = 0; c < MAX_CLIENTS; c++)
			if(Report.m_aDivergentPerClient[c])
				printf("%s:   client %d: %d divergent comparison(s), first at tick %d\n", aPath, c, Report.m_aDivergentPerClient[c], Report.m_aFirstDivergentTick[c]);

		if(Report.m_PositionsCompared == 0)
		{
			printf("%s: no player ever appeared alive in this recording, nothing to compare\n", aPath);
			continue;
		}
		AnyComparisonMade = true;

		if(Report.m_vFirstDivergences.empty())
		{
			printf("%s: all %d compared positions match exactly\n", aPath, Report.m_PositionsCompared);
			continue;
		}

		printf("%s: first %zu divergent comparison(s):\n", aPath, Report.m_vFirstDivergences.size());
		for(const CDivergence &D : Report.m_vFirstDivergences)
		{
			printf("%s:   tick=%d client=%d recorded=(%d,%d) replayed=(%d,%d)\n",
				aPath, D.m_Tick, D.m_ClientId, D.m_RecordedX, D.m_RecordedY, D.m_ReplayedX, D.m_ReplayedY);
		}

		char aSummary[IO_MAX_PATH_LENGTH + 128];
		str_format(aSummary, sizeof(aSummary), "%s: %d/%d divergent comparison(s) across %d tick(s), first at tick %d client %d",
			aPath, Report.m_DivergentComparisons, Report.m_PositionsCompared, Report.m_DivergentTicks,
			Report.m_vFirstDivergences[0].m_Tick, Report.m_vFirstDivergences[0].m_ClientId);
		DivergenceSummary += aSummary;
		DivergenceSummary += "\n";
	}

	ASSERT_TRUE(AnyComparisonMade) << "no recording in " << pDir << " produced a character to compare";

	if(!DivergenceSummary.empty())
	{
		GTEST_SKIP() << "replayed physics diverge from the recording in at least one file (see stdout above for the full per-tick findings):\n"
			     << DivergenceSummary;
	}
}
