// This file can be included several times.

UUID(TEEHISTORIAN_TEST, "teehistorian-test@ddnet.org")
UUID(TEEHISTORIAN_DDNETVER_OLD, "teehistorian-ddnetver-old@ddnet.org")
UUID(TEEHISTORIAN_DDNETVER, "teehistorian-ddnetver@ddnet.org")
UUID(TEEHISTORIAN_AUTH_INIT, "teehistorian-auth-init@ddnet.org")
UUID(TEEHISTORIAN_AUTH_LOGIN, "teehistorian-auth-login@ddnet.org")
UUID(TEEHISTORIAN_AUTH_LOGOUT, "teehistorian-auth-logout@ddnet.org")
UUID(TEEHISTORIAN_JOINVER6, "teehistorian-joinver6@ddnet.org")
UUID(TEEHISTORIAN_JOINVER7, "teehistorian-joinver7@ddnet.org")
UUID(TEEHISTORIAN_PLAYER_SWITCH, "teehistorian-player-swap@ddnet.org")
UUID(TEEHISTORIAN_SAVE_SUCCESS, "teehistorian-save-success@ddnet.org")
UUID(TEEHISTORIAN_SAVE_FAILURE, "teehistorian-save-failure@ddnet.org")
UUID(TEEHISTORIAN_LOAD_SUCCESS, "teehistorian-load-success@ddnet.org")
UUID(TEEHISTORIAN_LOAD_FAILURE, "teehistorian-load-failure@ddnet.org")
UUID(TEEHISTORIAN_PLAYER_TEAM, "teehistorian-player-team@ddnet.org")
UUID(TEEHISTORIAN_TEAM_PRACTICE, "teehistorian-team-practice@ddnet.org")
UUID(TEEHISTORIAN_PLAYER_READY, "teehistorian-player-ready@ddnet.org")
UUID(TEEHISTORIAN_PLAYER_REJOIN, "teehistorian-rejoinver6@ddnet.org")
UUID(TEEHISTORIAN_ANTIBOT, "teehistorian-antibot@ddnet.org")
UUID(TEEHISTORIAN_PLAYER_NAME, "teehistorian-player-name@ddnet.org")
UUID(TEEHISTORIAN_PLAYER_FINISH, "teehistorian-player-finish@ddnet.org")
UUID(TEEHISTORIAN_TEAM_FINISH, "teehistorian-team-finish@ddnet.org")
