#ifndef ENGINE_CLIENT_BACKEND_OPENGLES_GLES_CLASS_DEFINES_H
#define ENGINE_CLIENT_BACKEND_OPENGLES_GLES_CLASS_DEFINES_H
#undef ENGINE_CLIENT_BACKEND_OPENGLES_GLES_CLASS_DEFINES_H
#endif

#ifdef GLES_CLASS_DEFINES_DO_DEFINE
#define CCommandProcessorFragmentOpenGl3_3 CCommandProcessorFragmentOpenGLES3
#define CCommandProcessorFragmentOpenGl3 CCommandProcessorFragmentOpenGLES3Wrapper
#define CCommandProcessorFragmentOpenGl2 CCommandProcessorFragmentOpenGLES2
#define CCommandProcessorFragmentOpenGl CCommandProcessorFragmentOpenGLES

#define CGLSL CGLSL_ES
#define CGLSLProgram CGLSL_ESProgram
#define CGLSLTWProgram CGLSL_ESTWProgram
#define CGLSLTextProgram CGLSL_ESTextProgram
#define CGLSLPrimitiveProgram CGLSL_ESPrimitiveProgram
#define CGLSLPrimitiveExProgram CGLSL_ESPrimitiveExProgram
#define CGLSLSpriteMultipleProgram CGLSL_ESSpriteMultipleProgram
#define CGLSLQuadProgram CGLSL_ESQuadProgram
#define CGLSLTileProgram CGLSL_ESTileProgram
#else
#undef CCommandProcessorFragmentOpenGl3_3
#undef CCommandProcessorFragmentOpenGl3
#undef CCommandProcessorFragmentOpenGl2
#undef CCommandProcessorFragmentOpenGl

#undef CGLSL
#undef CGLSLProgram
#undef CGLSLTWProgram
#undef CGLSLTextProgram
#undef CGLSLPrimitiveProgram
#undef CGLSLPrimitiveExProgram
#undef CGLSLSpriteMultipleProgram
#undef CGLSLQuadProgram
#undef CGLSLTileProgram
#endif
