image: ubuntu:22.04

stages:
  - test


build_cmake:
  before_script:
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install
      pkg-config
      clang rustc
      cargo cmake ninja-build
      libfreetype6-dev libnotify-dev libsdl3-dev libsqlite3-dev libvulkan-dev
      glslang-tools spirv-tools libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev
      libx264-dev libpng-dev
      libcurl4 libcurl3-gnutls libcurl4-openssl-dev libcurlpp-dev
      libogg-dev libopus-dev libopusfile-dev
      valgrind -y
  stage: test
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j$(nproc)
