[workspace]
members = [
  ".",
  "cli",
]

[package]
name = "asdf"
version = "0.0.0"
edition = "2021"
rust-version = "1.85"
publish = false
license = "Zlib"

[dependencies]
anyhow = "1.0.66"
derive_more = { version = "2.1", features = ["from"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
ipnet = { version = "2.9.0", features = ["serde"] }
jiff = { version = "0.2.32", default-features = false, features = ["serde", "std"] }
log = "0.4.34"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0.64"
serde_with = "3.21.0"
tokio = { version = "1.43.0", features = ["io-util", "net", "rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["macros"] }
tokio-util = { version = "0.7", features = ["io"] }
