if(NOT WIN32)
	find_package(PkgConfig REQUIRED QUIET)
	pkg_check_modules(PC_GLIB REQUIRED QUIET glib-2.0)
endif()

find_path(GLIB_INCLUDEDIR glib.h
	PATH_SUFFIXES glib-2.0
	HINTS ${PC_GLIB_INCLUDE_DIRS} ${PC_GLIB_INCLUDEDIR})

find_path(GLIBCONF_INCLUDEDIR glibconfig.h
	PATH_SUFFIXES glib-2.0/include ../lib/glib-2.0/include
	HINTS ${PC_GLIB_INCLUDE_DIRS} ${PC_GLIB_LIBRARIES} ${CMAKE_SYSTEM_LIBRARY_PATH})

find_library(GLIB_LIBRARY
	NAMES glib-2.0
	HINTS ${PC_GLIB_LIBRARY_DIRS} ${PC_GLIB_LIBDIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLib DEFAULT_MSG GLIB_INCLUDEDIR GLIBCONF_INCLUDEDIR GLIB_LIBRARY)

mark_as_advanced(GLIB_INCLUDEDIR GLIBCONF_INCLUDEDIR GLIB_LIBRARY)

set(GLIB_INCLUDE_DIRS ${GLIB_INCLUDEDIR} ${GLIBCONF_INCLUDEDIR})
set(GLIB_LIBRARIES ${GLIB_LIBRARY})
