# the android toolchain sets the paths right
FIND_LIBRARY(ANDROID_LIBRARY_EGL
  EGL
)

FIND_LIBRARY(ANDROID_LIBRARY_GLES1
  GLESv1_CM
)

FIND_LIBRARY(ANDROID_LIBRARY_GLES2
  GLESv2
)

FIND_LIBRARY(ANDROID_LIBRARY_GLES3
  GLESv3
)

FIND_LIBRARY(ANDROID_LIBRARY_LOG
  log
)

FIND_LIBRARY(ANDROID_LIBRARY_ANDROID
  android
)

FIND_LIBRARY(ANDROID_LIBRARY_OPENSLES
  OpenSLES
)

set(TW_ANDROID_LIBS
  ${ANDROID_LIBRARY_LOG}
  ${ANDROID_LIBRARY_ANDROID}
)

set(TW_ANDROID_LIBS_CLIENT
  ${TW_ANDROID_LIBS}
  ${ANDROID_LIBRARY_EGL}
  ${ANDROID_LIBRARY_GLES1}
  ${ANDROID_LIBRARY_GLES2}
  ${ANDROID_LIBRARY_GLES3}
  ${ANDROID_LIBRARY_OPENSLES}
)
