if(NOT CMAKE_CROSSCOMPILING)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_WAVPACK wavpack)
endif()

set_extra_dirs_lib(WAVPACK wavpack)
find_library(WAVPACK_LIBRARY
  NAMES wavpack
  HINTS ${HINTS_WAVPACK_LIBDIR} ${PC_WAVPACK_LIBDIR} ${PC_WAVPACK_LIBRARY_DIRS}
  PATHS ${PATHS_WAVPACK_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
set_extra_dirs_include(WAVPACK wavpack "${WAVPACK_LIBRARY}")
find_path(WAVPACK_INCLUDEDIR wavpack.h
  PATH_SUFFIXES wavpack
  HINTS ${HINTS_WAVPACK_INCLUDEDIR} ${PC_WAVPACK_INCLUDE_DIRS}
  PATHS ${PATHS_WAVPACK_INCLUDEDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Wavpack DEFAULT_MSG WAVPACK_LIBRARY WAVPACK_INCLUDEDIR)

mark_as_advanced(WAVPACK_LIBRARY WAVPACK_INCLUDEDIR)

set(WAVPACK_LIBRARIES ${WAVPACK_LIBRARY})
set(WAVPACK_INCLUDE_DIRS ${WAVPACK_INCLUDEDIR})

if(WAVPACK_FOUND)
  is_bundled(WAVPACK_BUNDLED "${WAVPACK_LIBRARY}")
  if(WAVPACK_BUNDLED AND TARGET_OS STREQUAL "windows")
    set(WAVPACK_COPY_FILES
      "${EXTRA_WAVPACK_LIBDIR}/libwavpack-1.dll"
    )
  else()
    set(WAVPACK_COPY_FILES)
  endif()
endif()
