// This file can be included several times.

#undef KEY_FIRST
#undef KEY_UNKNOWN
#undef KEY_A
#undef KEY_B
#undef KEY_C
#undef KEY_D
#undef KEY_E
// #undef KEY_F
#undef KEY_G
#undef KEY_H
#undef KEY_I
#undef KEY_J
#undef KEY_K
#undef KEY_L
#undef KEY_M
#undef KEY_N
#undef KEY_O
#undef KEY_P
#undef KEY_Q
#undef KEY_R
#undef KEY_S
#undef KEY_T
#undef KEY_U
#undef KEY_V
#undef KEY_W
#undef KEY_X
#undef KEY_Y
#undef KEY_Z
#undef KEY_1
#undef KEY_2
#undef KEY_3
#undef KEY_4
#undef KEY_5
#undef KEY_6
#undef KEY_7
#undef KEY_8
#undef KEY_9
#undef KEY_0
#undef KEY_RETURN
#undef KEY_ESCAPE
#undef KEY_BACKSPACE
#undef KEY_TAB
#undef KEY_SPACE
#undef KEY_MINUS
#undef KEY_EQUALS
#undef KEY_LEFTBRACKET
#undef KEY_RIGHTBRACKET
#undef KEY_BACKSLASH
#undef KEY_NONUSHASH
#undef KEY_SEMICOLON
#undef KEY_APOSTROPHE
#undef KEY_GRAVE
#undef KEY_COMMA
#undef KEY_PERIOD
#undef KEY_SLASH
#undef KEY_CAPSLOCK
#undef KEY_F1
#undef KEY_F2
#undef KEY_F3
#undef KEY_F4
#undef KEY_F5
#undef KEY_F6
#undef KEY_F7
#undef KEY_F8
#undef KEY_F9
#undef KEY_F10
#undef KEY_F11
#undef KEY_F12
#undef KEY_PRINTSCREEN
#undef KEY_SCROLLLOCK
#undef KEY_PAUSE
#undef KEY_INSERT
#undef KEY_HOME
#undef KEY_PAGEUP
#undef KEY_DELETE
#undef KEY_END
#undef KEY_PAGEDOWN
#undef KEY_RIGHT
#undef KEY_LEFT
#undef KEY_DOWN
#undef KEY_UP
#undef KEY_NUMLOCKCLEAR
#undef KEY_KP_DIVIDE
#undef KEY_KP_MULTIPLY
#undef KEY_KP_MINUS
#undef KEY_KP_PLUS
#undef KEY_KP_ENTER
#undef KEY_KP_1
#undef KEY_KP_2
#undef KEY_KP_3
#undef KEY_KP_4
#undef KEY_KP_5
#undef KEY_KP_6
#undef KEY_KP_7
#undef KEY_KP_8
#undef KEY_KP_9
#undef KEY_KP_0
#undef KEY_KP_PERIOD
#undef KEY_NONUSBACKSLASH
#undef KEY_APPLICATION
#undef KEY_POWER
#undef KEY_KP_EQUALS
#undef KEY_F13
#undef KEY_F14
#undef KEY_F15
#undef KEY_F16
#undef KEY_F17
#undef KEY_F18
#undef KEY_F19
#undef KEY_F20
#undef KEY_F21
#undef KEY_F22
#undef KEY_F23
#undef KEY_F24
#undef KEY_EXECUTE
#undef KEY_HELP
#undef KEY_MENU
#undef KEY_SELECT
#undef KEY_STOP
#undef KEY_AGAIN
#undef KEY_UNDO
#undef KEY_CUT
#undef KEY_COPY
#undef KEY_PASTE
#undef KEY_FIND
#undef KEY_MUTE
#undef KEY_VOLUMEUP
#undef KEY_VOLUMEDOWN
#undef KEY_KP_COMMA
#undef KEY_KP_EQUALSAS400
#undef KEY_INTERNATIONAL1
#undef KEY_INTERNATIONAL2
#undef KEY_INTERNATIONAL3
#undef KEY_INTERNATIONAL4
#undef KEY_INTERNATIONAL5
#undef KEY_INTERNATIONAL6
#undef KEY_INTERNATIONAL7
#undef KEY_INTERNATIONAL8
#undef KEY_INTERNATIONAL9
#undef KEY_LANG1
#undef KEY_LANG2
#undef KEY_LANG3
#undef KEY_LANG4
#undef KEY_LANG5
#undef KEY_LANG6
#undef KEY_LANG7
#undef KEY_LANG8
#undef KEY_LANG9
#undef KEY_ALTERASE
#undef KEY_SYSREQ
#undef KEY_CANCEL
#undef KEY_CLEAR
#undef KEY_PRIOR
#undef KEY_RETURN2
#undef KEY_SEPARATOR
#undef KEY_OUT
#undef KEY_OPER
#undef KEY_CLEARAGAIN
#undef KEY_CRSEL
#undef KEY_EXSEL
#undef KEY_KP_00
#undef KEY_KP_000
#undef KEY_THOUSANDSSEPARATOR
#undef KEY_DECIMALSEPARATOR
#undef KEY_CURRENCYUNIT
#undef KEY_CURRENCYSUBUNIT
#undef KEY_KP_LEFTPAREN
#undef KEY_KP_RIGHTPAREN
#undef KEY_KP_LEFTBRACE
#undef KEY_KP_RIGHTBRACE
#undef KEY_KP_TAB
#undef KEY_KP_BACKSPACE
#undef KEY_KP_A
#undef KEY_KP_B
#undef KEY_KP_C
#undef KEY_KP_D
#undef KEY_KP_E
#undef KEY_KP_F
#undef KEY_KP_XOR
#undef KEY_KP_POWER
#undef KEY_KP_PERCENT
#undef KEY_KP_LESS
#undef KEY_KP_GREATER
#undef KEY_KP_AMPERSAND
#undef KEY_KP_DBLAMPERSAND
#undef KEY_KP_VERTICALBAR
#undef KEY_KP_DBLVERTICALBAR
#undef KEY_KP_COLON
#undef KEY_KP_HASH
#undef KEY_KP_SPACE
#undef KEY_KP_AT
#undef KEY_KP_EXCLAM
#undef KEY_KP_MEMSTORE
#undef KEY_KP_MEMRECALL
#undef KEY_KP_MEMCLEAR
#undef KEY_KP_MEMADD
#undef KEY_KP_MEMSUBTRACT
#undef KEY_KP_MEMMULTIPLY
#undef KEY_KP_MEMDIVIDE
#undef KEY_KP_PLUSMINUS
#undef KEY_KP_CLEAR
#undef KEY_KP_CLEARENTRY
#undef KEY_KP_BINARY
#undef KEY_KP_OCTAL
#undef KEY_KP_DECIMAL
#undef KEY_KP_HEXADECIMAL
#undef KEY_LCTRL
#undef KEY_LSHIFT
#undef KEY_LALT
#undef KEY_LGUI
#undef KEY_RCTRL
#undef KEY_RSHIFT
#undef KEY_RALT
#undef KEY_RGUI
#undef KEY_MODE
#undef KEY_AUDIONEXT
#undef KEY_AUDIOPREV
#undef KEY_AUDIOSTOP
#undef KEY_AUDIOPLAY
#undef KEY_AUDIOMUTE
#undef KEY_MEDIASELECT
#undef KEY_WWW
#undef KEY_MAIL
#undef KEY_CALCULATOR
#undef KEY_COMPUTER
#undef KEY_AC_SEARCH
#undef KEY_AC_HOME
#undef KEY_AC_BACK
#undef KEY_AC_FORWARD
#undef KEY_AC_STOP
#undef KEY_AC_REFRESH
#undef KEY_AC_BOOKMARKS
#undef KEY_BRIGHTNESSDOWN
#undef KEY_BRIGHTNESSUP
#undef KEY_DISPLAYSWITCH
#undef KEY_KBDILLUMTOGGLE
#undef KEY_KBDILLUMDOWN
#undef KEY_KBDILLUMUP
#undef KEY_EJECT
#undef KEY_SLEEP
#undef KEY_APP1
#undef KEY_APP2
#undef KEY_MOUSE_1
#undef KEY_MOUSE_2
#undef KEY_MOUSE_3
#undef KEY_MOUSE_4
#undef KEY_MOUSE_5
#undef KEY_MOUSE_6
#undef KEY_MOUSE_7
#undef KEY_MOUSE_8
#undef KEY_MOUSE_9
#undef KEY_MOUSE_WHEEL_UP
#undef KEY_MOUSE_WHEEL_DOWN
#undef KEY_MOUSE_WHEEL_LEFT
#undef KEY_MOUSE_WHEEL_RIGHT
#undef KEY_LAST
