#ifndef GAME_CLIENT_COMPONENTS_CHILLERBOT_VERSION_H
#define GAME_CLIENT_COMPONENTS_CHILLERBOT_VERSION_H

#define CHILLERBOT_BUILD_DATE __DATE__ ", " __TIME__
#define CHILLERBOT_VERSIONNR 003
#define CHILLERBOT_VERSION "0.0.3"

#endif
